### PR TITLE
Windows portable zip/MSI package builds

### PR DESCRIPTION
**Pull request by someone--else**
MSIX thing didn't work out (too much work to support backward compatibility for little benefit); MSI should support Windows 7 to 10 and is built via open-source WiX tool

Portable ZIP and MSI packages include all required GTK binaries and icons/themes (there isn't an easy way to install these on Windows without MSYS/MinGW). Licenses for GTK and dependent libraries are also included in the license subdir of the installation folder, but not in the MSI package license dialog - if they should be, source text is at glscopeclient/wix/LICENSE.rtf (yes MSI/WiX don't support plain text licenses)

### CODE REVIEW

**Comment by someone--else** [comment]
Built portable ZIP/MSI packages can be downloaded from here: https://github.com/someone--else/scopehal-apps/actions/runs/865264938
(MSI is zipped because GitHub Actions)

**Comment by someone--else** [comment]
#348

**Comment by azonenberg** [comment]
Please include all dependency licenses in the license.rtf file. Looks good at a glance otherwise although I need to test a bit more thoroughly before merging.

**Comment by someone--else** [comment]
Added dependency licenses to LICENSE.rtf; although it's not very clear what license applies to what file since it's just a concatenation of all relevant license files. Not sure how it should be structured to reflect that

**Comment by azonenberg** [comment]
> Added dependency licenses to LICENSE.rtf; although it's not very clear what license applies to what file since it's just a concatenation of all relevant license files. Not sure how it should be structured to reflect that

I'm thinking one heading per unique license (no need to include e.g. the LGPL more than once) that specifies what particular binaries/directories are covered under it.

**Comment by someone--else** [comment]
Looked at a few cases and often license texts are customized with at least different copyright strings. Not sure it would be entirely correct to delete that

**Comment by someone--else** [comment]
There's also an option of deleting the license dialog from the installer entirely; might be acceptable since portable zip package doesn't have one either

**Comment by azonenberg** [comment]
Looks like we've got some merge conflicts to take care of still. I think all of the recent Windows build failures have been resolved. Anything needed on my end to help this proceed?

**Comment by someone--else** [comment]
Rebased to the current master branch; resulting build (https://github.com/someone--else/scopehal-apps/actions/runs/958775342) generates fully functional zip and MSI packages

**Pull request merged**
