### PR TITLE
ci/msys2: FFTS is now available in MSYS2 repos

### PR DESCRIPTION
**Pull request by umarcor**
scopehal does not have an strong dependency on the master branch of FFTS. Moreover, FFTS is not updated frequently. Since FFTS is now available in MSYS2 repos, I believe there is no point in buiding it from sources here. Instead, this PR installs FFT through pacman, as done with other dependencies.

### CODE REVIEW

**Comment by azonenberg** [comment]
Please also update the build instructions in the README file and scopehal-docs to reflect that FFTS no longer has to be built from source on Windows.

**Comment by umarcor** [comment]
Should that be done before or after merging this change into master?

**Comment by azonenberg** [comment]
> Should that be done before or after merging this change into master?

Push the change to scopehal-docs first. Then change the README in this repo and update the scopehal-docs submodule reference as part of this PR. That way we get an atomic switchover.

**Comment by umarcor** [comment]
I updated the doc submodule. I'm not sure the README needs to be updated, since it points to the docs in the section about Windows.

**Pull request merged**
